
export const UPDATE_MACHINE_TYPES_FIELD_VALUE  = 'UPDATE_MACHINE_TYPES_FIELD_VALUE';
export const DELETE_MACHINE  = 'DELETE_MACHINE';

export const ADD_MACHINE  = 'ADD_MACHINE';

export const UPDATE_MACHINE_TYPES_FIELD  = 'UPDATE_MACHINE_TYPES_FIELD';
export const DELETE_MACHINE_TYPES_FIELD  = 'DELETE_MACHINE_TYPES_FIELD';
export const ADD_MACHINE_TYPES_FIELD  = 'ADD_MACHINE_TYPES_FIELD';

export const DELETE_MACHINE_TYPE  = 'DELETE_MACHINE_TYPE';
export const ADD_MACHINE_TYPE  = 'ADD_MACHINE_TYPE';

export const UPDATE_MACHINE_TYPE  = 'UPDATE_MACHINE_TYPE';



